model: "UNETR"
cuda: true
data_path: "/OV-data/keramika/source/data/input/train_data_x_weak.tif"
label_path: "/OV-data/keramika/source/data/output/train_data_y_weak.tif"
output_dir: "./output/SwinUNETR"
tensorboard_dir: "./runs"
epochs: 400
learning_rate: 0.0001