# General
cuda: true
mode: "inference"

# Training
data_path: "/OV-data/keramika/source/data/input/train_data_x_weak.tif"
label_path: "/OV-data/keramika/source/data/output/train_data_y_weak.tif"
output_dir: "./output/UNETR"
tensorboard_dir: "./runs"
epochs: 601
learning_rate: 0.0001
dropout_rate: 0.1
train_split: 0.8

# Inference
pretrained_model_path: "/home/bar/UNETR/output/UNETR/UNETR/2025-05-19_12:59:07/final-model.pt"